### ISSUE TITLE
Code and Functionality Cleanup

### ISSUE THREAD

**Issue by CarlaHofmann** [CarlaHofmann/exercise-generator-fe#114]
- [x] check used/published logic #91 
- [x] Order Buttons #71 
- [x] Representation of backend queries in the frontend #41 
   - [x] Insert "Nothing found" for tables / backend queries. CSS: .no-data-found-text
   - [x] Loading spinner for backend queries
   - [x] TimeOut für Spinner
   - [x] Adapt pages to what I can't do I can't see
- [x] Prevent loss of edited pages without saving #35
